name: Plain Language Summary Issue Form
description: Report issues with plain language summaries using a structured form
title: "[SUMMARY ISSUE]: "
labels:
  - summary improvement
assignees:
  - octocat
body:
  - type: dropdown
    id: package-file
    attributes:
      label: Package and File
      description: Select the package and file with the issue
      options:
        - fhir.base.template (ig-template-base)
        - fhir.efss (efss)
        - hl7.base.template (ig-template-hl7)
        - hl7.ca.fhir.template (ig-template-ca)
        - hl7.cda.template (ig-template-cda)
        - hl7.cda.us.ccda (CDA-ccda)
        - hl7.cda.us.ccda (CDA-ccda-2.1-sd)
        - hl7.cda.us.ccdar2dot2 (CDA-ccda-2.2)
        - hl7.cda.us.eyecare (cda-eyecare)
        - hl7.cda.uv.core (CDA-core-2.0)
        - hl7.cda.uv.core (CDA-core-sd)
        - hl7.cda.uv.ips (CDA-IPS)
        - hl7.cql (cql)
        - hl7.davinci.template (ig-template-davinci)
        - hl7.ehrsfmr21.base (ehrsfm-ig)
        - hl7.extensions.template (ig-template-extensions)
        - hl7.fast.template (ig-template-fast)
        - hl7.fhir.affiliate.template (ig-template-affiliate)
        - hl7.fhir.template (ig-template-fhir)
        - hl7.fhir.us.bfdr (fhir-bfdr)
        - hl7.fhir.us.bhp (us-behavioral-health-profiles)
        - hl7.fhir.us.breast-radiology (fhir-breast-radiology-ig)
        - hl7.fhir.us.bser (bser)
        - hl7.fhir.us.cancer-reporting (cancer-reporting)
        - hl7.fhir.us.cardx-htn (cardx-ig)
        - hl7.fhir.us.carin-bb (carin-bb)
        - hl7.fhir.us.ccda (ccda-on-fhir)
        - hl7.fhir.us.cdmh (cdmh)
        - hl7.fhir.us.central-cancer-registry-reporting
          (fhir-central-cancer-registry-reporting-ig)
        - hl7.fhir.us.cimilabs (cimi-labs)
        - hl7.fhir.us.codex-radiation-therapy (codex-radiation-therapy)
        - hl7.fhir.us.consent-management (fhir-consent-management)
        - hl7.fhir.us.core (US-Core)
        - hl7.fhir.us.covid19library (fhir-COVID19Library-ig)
        - hl7.fhir.us.cqfmeasures (cqf-measures)
        - hl7.fhir.us.davinci-alerts (davinci-alerts)
        - hl7.fhir.us.davinci-atr (davinci-atr)
        - hl7.fhir.us.davinci-cdex (davinci-ecdx)
        - hl7.fhir.us.davinci-crd (davinci-crd)
        - hl7.fhir.us.davinci-deqm (davinci-deqm)
        - hl7.fhir.us.davinci-drug-formulary (davinci-pdex-formulary)
        - hl7.fhir.us.davinci-dtr (davinci-dtr)
        - hl7.fhir.us.davinci-hrex (davinci-ehrx)
        - hl7.fhir.us.davinci-pas (davinci-pas)
        - hl7.fhir.us.davinci-pcde (davinci-pcde)
        - hl7.fhir.us.davinci-pct (davinci-pct)
        - hl7.fhir.us.davinci-pdex (davinci-epdx)
        - hl7.fhir.us.davinci-pdex-plan-net (davinci-pdex-plan-net)
        - hl7.fhir.us.davinci-pr (davinci-pr)
        - hl7.fhir.us.davinci-ra (davinci-ra)
        - hl7.fhir.us.davinci-vbpr (davinci-vbpr)
        - hl7.fhir.us.dental-data-exchange (dental-data-exchange)
        - hl7.fhir.us.directory-attestation (fhir-directory-attestation)
        - hl7.fhir.us.directory-exchange (fhir-directory-exchange)
        - hl7.fhir.us.directory-query (fhir-directory-query)
        - hl7.fhir.us.dme-orders (dme-orders)
        - hl7.fhir.us.ecr (case-reporting)
        - hl7.fhir.us.eltss (eLTSS)
        - hl7.fhir.us.exchange-routing (fhir-exchange-routing-ig)
        - hl7.fhir.us.hai (HAI)
        - hl7.fhir.us.hai-ltcf (HAI-LTCF)
        - hl7.fhir.us.health-care-surveys-reporting
          (fhir-health-care-surveys-reporting-ig)
        - hl7.fhir.us.home-lab-report (home-lab-report)
        - hl7.fhir.us.hsds (FHIR-IG-Human-Services-Directory)
        - hl7.fhir.us.icsr-ae-reporting (fhir-icsr-ae-reporting)
        - hl7.fhir.us.identity-matching (fhir-identity-matching-ig)
        - hl7.fhir.us.illTraveler (ReportIIITraveler-ig)
        - hl7.fhir.us.insurance-card (carin-digital-insurance-card)
        - hl7.fhir.us.lower-extremity-skin-wound-assessment (fhir-skin-wound-ig)
        - hl7.fhir.us.mcc (fhir-us-mcc)
        - hl7.fhir.us.mcode (fhir-mCODE-ig)
        - hl7.fhir.us.mdi (fhir-mdi-ig)
        - hl7.fhir.us.medication-rems (fhir-medication-rems-ig)
        - hl7.fhir.us.medmorph (fhir-medmorph)
        - hl7.fhir.us.medmorph-research-dex (fhir-medmorph-research-dex-ig)
        - hl7.fhir.us.mihr (fhir-mmm-ig)
        - hl7.fhir.us.military-service (fhir-military-service)
        - hl7.fhir.us.ndh (fhir-us-ndh)
        - hl7.fhir.us.nhsn-ade (fhir-nhsn-ade-ig)
        - hl7.fhir.us.nhsn-dqm (nhsn-dqm)
        - hl7.fhir.us.odh (us-odh)
        - hl7.fhir.us.pacio-adi (fhir-pacio-adi)
        - hl7.fhir.us.pacio-adi (pacio-adi)
        - hl7.fhir.us.pacio-cs (fhir-pacio-cognitive-status)
        - hl7.fhir.us.pacio-fs (fhir-pacio-functional-status)
        - hl7.fhir.us.pacio-pfe (fhir-pacio-pfe)
        - hl7.fhir.us.pacio-rt (fhir-pacio-rt)
        - hl7.fhir.us.pdmp (fhir-pdmp)
        - hl7.fhir.us.ph-library (fhir-us-ph-common-library-ig)
        - hl7.fhir.us.ph-library (fhir-us-phpl)
        - hl7.fhir.us.ph-library (fhir-us-ph-library)
        - hl7.fhir.us.physical-activity (physical-activity)
        - hl7.fhir.us.pq-cmc-fda (FHIR-us-pq-cmc-fda)
        - hl7.fhir.us.qicore (fhir-qi-core)
        - hl7.fhir.us.registry-protocols (fhir-registry-protocols-ig)
        - hl7.fhir.us.resp-net (fhir-resp-net-ig)
        - hl7.fhir.us.sdoh-clinicalcare (fhir-sdoh-clinicalcare)
        - hl7.fhir.us.sirb (fhir-sirb)
        - hl7.fhir.us.smp (smp-ig)
        - hl7.fhir.us.specialty-rx (fhir-specialty-rx)
        - hl7.fhir.us.spl (fhir-spl)
        - hl7.fhir.us.udap-security (fhir-udap-security-ig)
        - hl7.fhir.us.vitals (cimi-vital-signs)
        - hl7.fhir.us.vr-common-library (vr-common-library)
        - hl7.fhir.us.vrdr (vrdr)
        - hl7.fhir.uv.adverseeventclinicalcare (fhir-ae-care-ig)
        - hl7.fhir.uv.ae-research-backport-ig (fhir-ae-research-backport-ig)
        - hl7.fhir.uv.ae-research-ig (fhir-ae-research-ig)
        - hl7.fhir.uv.application-feature (capstmt)
        - hl7.fhir.uv.bulkdata (bulk-data)
        - hl7.fhir.uv.cardx-htn-mng (CardX-HTN-MNG)
        - hl7.fhir.uv.cdisc-mapping (fhir-cdisc-mapping)
        - hl7.fhir.uv.cgm (cgm)
        - hl7.fhir.uv.cmi (Content-Management-Infrastructure-IG)
        - hl7.fhir.uv.cow (fhir-cow-ig)
        - hl7.fhir.uv.cpg (cqf-recommendations)
        - hl7.fhir.uv.cql (cql-ig)
        - hl7.fhir.uv.crmi (crmi-ig)
        - hl7.fhir.uv.dap (data-access-policies)
        - hl7.fhir.uv.deval (DeviceAlerting)
        - hl7.fhir.uv.dicom-sr (dicom-sr)
        - hl7.fhir.uv.ebm (ebm)
        - hl7.fhir.uv.ehrs-rle (ehrs-rle-ig)
        - hl7.fhir.uv.emedicinal-product-info (emedicinal-product-info)
        - hl7.fhir.uv.extensions (fhir-extensions)
        - hl7.fhir.uv.eyecare (fhir-eyecare-ig)
        - hl7.fhir.uv.fhir-clinical-document (fhir-clinical-document)
        - hl7.fhir.uv.fhir-for-fair (fhir-for-fair)
        - hl7.fhir.uv.fhircast (fhircast-docs)
        - hl7.fhir.uv.fhirpath (FHIRPath)
        - hl7.fhir.uv.genomics-reporting (genomics-reporting)
        - hl7.fhir.uv.ibcm (fetal_records)
        - hl7.fhir.uv.ichom.breastcancer (fhir-ichom-breast-cancer-ig)
        - hl7.fhir.uv.ihe-sdc-ecc (ihe-sdc-ecc-on-fhir)
        - hl7.fhir.uv.imaging-service-request-ig (imaging-service-request-ig)
        - hl7.fhir.uv.ipa (fhir-ipa)
        - hl7.fhir.uv.ips (fhir-ips)
        - hl7.fhir.uv.lab-report (uv-lab-rep-ig)
        - hl7.fhir.uv.livd (livd)
        - hl7.fhir.uv.omop (fhir-omop-ig)
        - hl7.fhir.uv.order-catalog (fhir-order-catalog)
        - hl7.fhir.uv.patient-corrections (fhir-patient-correction)
        - hl7.fhir.uv.pddi (PDDI-CDS)
        - hl7.fhir.uv.pharm-quality (uv-dx-pq)
        - hl7.fhir.uv.phd (phd)
        - hl7.fhir.uv.phenomics-exchange (phenomics-exchange-ig)
        - hl7.fhir.uv.pocd (uv-pocd)
        - hl7.fhir.uv.radiation-dose-summary (fhir-radiation-dose-summary-ig)
        - hl7.fhir.uv.rtls (rtls-ig)
        - hl7.fhir.uv.saner (fhir-saner)
        - hl7.fhir.uv.sdc (sdc)
        - hl7.fhir.uv.security-label-ds4p (fhir-security-label-ds4p)
        - hl7.fhir.uv.shc-vaccination (fhir-shc-vaccination-ig)
        - hl7.fhir.uv.shorthand (fhir-shorthand)
        - hl7.fhir.uv.smart-app-launch (smart-app-launch)
        - hl7.fhir.uv.smart-health-cards-and-links (smart-health-cards-and-links)
        - hl7.fhir.uv.smart-web-messaging (smart-web-messaging)
        - hl7.fhir.uv.subscriptions-backport (fhir-subscription-backport-ig)
        - hl7.fhir.uv.termchangeset (termchangeset-ig)
        - hl7.fhir.uv.termfundamentals (terminology-fundamentals-ig)
        - hl7.fhir.uv.v2mappings (v2-to-fhir)
        - hl7.fhir.uv.vhdir (VhDir)
        - hl7.fhir.uv.vulcan-rwd (vulcan-rwd)
        - hl7.fhir.uv.vulcan-soa (Vulcan-schedule-ig)
        - hl7.fhir.uv.xver (fhir-cross-version)
        - hl7.gravity.template (ig-template-gravity)
        - hl7.other.template (ig-template-other)
        - hl7.other.uv.cds-hooks (cds-hooks)
        - hl7.other.uv.cds.hooks.library (cds-hooks-library)
        - hl7.terminology (UTG)
        - hl7.utg.template (ig-template-utg)
        - hl7.vulcan.template (ig-template-vulcan)
        - hl7.xprod.uv.gender-harmony (fhir-gender-harmony)
        - StandardPatientHealthRecordIG (standard-patient-health-record-ig)
        - StandardPatientHealthRecordIG (personal-health-record-format-ig)
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Describe what's incorrect or misleading in the current summary. This rationale is critical because it will help the LLM summarizer avoid making the same mistake in the future.
      placeholder: The summary states X, but this is inaccurate because...
    validations:
      required: true
  - type: dropdown
    id: impact-level
    attributes:
      label: Impact Level
      description: How significant is this issue?
      options:
        - Minor (small inaccuracy, doesn't affect understanding)
        - Moderate (may lead to misunderstanding)
        - Major (significantly misleading or incorrect)
    validations:
      required: true
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: Provide a more accurate explanation or summary
